### ISSUE TITLE
Bug Report: Item Duplication with Create Mod

### ISSUE THREAD

**Issue by tpdjg** [Salandora/SophisticatedStorage#70]
When using SophisticatedStorage with Create, inserting items via a Create funnel into a SophisticatedStorage input port causes duplication if the storage network does not already contain that item.

**Steps to reproduce the behavior**
1. Place any **Create funnel** to input into the sophisticatedstorage:storage_input(Connected to the controller).
2. Throw or use a conveyor belt to input items into the funnel while the storage network does not already contain that item.

**Expected behavior**
There will be double the amount of the items appeared.

**Versions**
Fabric v1.20.1
SophisticatedStorage 1.0.10.1.100
Create 0.5.1-j-build.1631
fabric-api-0.92.3+1.20.1
fabric 1.20.1-0.16.10

**Comment by Salandora** [comment]
Your SophisticatedStorage and therefor SophisticatedCore version is quite old.
Try to update both as this bug should be fixed in newer versions.

**Comment by SodaSyrup** [comment]
issue still persists on newest version of both mods on fabric 1.20.1 by spinning a double chest in a create contraption, also voids every single item except the first slot when sophisticated storage container is part of a create contraption
